name: snapcart
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

#........PACKAGES......................#
dependencies:
  flutter:
    sdk: flutter
    #Utilitu packages

    http: ^1.3.0
    intl: ^0.20.2
    logger: ^2.5.0
    url_launcher: ^6.3.1

  #....ICONS

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  #STATE MANAGEMENT.....
  get: ^4.7.2
  get_storage: ^2.1.1
  #PRODUCT SPECIFIC........

#...........PACKGES ENDED............

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #...........LOCAL ASSETS
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/

  #........LOCAL FONTSS

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
          style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
